version: '3'
services:
    
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit-topic
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    
  sender:
    image: sender-topic
    build: 
      context: ./sender
      dockerfile: Dockerfile-dev
    container_name: sender-topic
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./sender/src:/usr/src/app/src:z

  receiver1:
    image: receiver-topic
    build: 
      context: ./receiver
      dockerfile: Dockerfile-dev
    container_name: receiver1-topic
    environment:
     - ROUTES=topic.1,topic.2
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./receiver/src:/usr/src/app/src:z

  receiver2:
    image: receiver-topic
    build: 
      context: ./receiver
      dockerfile: Dockerfile-dev
    container_name: receiver2-topic
    environment:
     - ROUTES=topic.#
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./receiver/src:/usr/src/app/src:z
